# Generated by Django 2.2.12 on 2021-12-15 16:58

from django.db import migrations, models
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_1', models.CharField(max_length=20)),
                ('user_2', models.CharField(max_length=20)),
                ('msgs', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
